import streamlit as st
import feedparser
from dateutil import parser  # Handles date strings
from feedgen.feed import FeedGenerator # For the XML export

# 1. Setup
st.set_page_config(page_title="Pro RSS Dashboard", layout="wide")

# 2. Sidebar Configuration
st.sidebar.title("Settings")
search_query = st.sidebar.text_input("🔍 Search keywords", "").lower()

# Add your feeds here
feed_list = [
    "https://www.nasa.gov/rss/dyn/breaking_news.rss",
    "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    "https://feeds.bbci.co.uk/news/rss.xml"
]

st.title("🗂️ Personal News Engine")

all_entries = []

# 3. Fetching Logic
with st.spinner('Syncing feeds...'):
    for url in feed_list:
        try:
            feed = feedparser.parse(url)
            for entry in feed.entries:
                # Store source name inside the entry
                entry['source_name'] = feed.feed.get('title', 'Unknown Source')
                all_entries.append(entry)
        except Exception as e:
            st.sidebar.warning(f"Could not load: {url}")

# 4. Sorting
all_entries.sort(
    key=lambda x: parser.parse(x.get('published', 'Jan 1 1900')), 
    reverse=True
)

# 5. Filtering
if search_query:
    filtered_entries = [
        e for e in all_entries 
        if search_query in e.title.lower() or search_query in e.get('summary', '').lower()
    ]
else:
    filtered_entries = all_entries

# 6. Sidebar Export Logic (The fix is here)
st.sidebar.markdown("---") # This replaces .divider() for better compatibility
st.sidebar.subheader("Export Results")

if st.sidebar.button("Generate XML"):
    fg = FeedGenerator()
    fg.title(f"Filtered Feed")
    fg.link(href="http://localhost", rel="self")
    fg.description("Generated by Streamlit RSS App")

    for entry in filtered_entries[:20]:
        fe = fg.add_entry()
        fe.title(entry.title)
        fe.link(href=entry.link)
        
    rss_xml = fg.rss_str(pretty=True)
    
    st.sidebar.download_button(
        label="📥 Download XML",
        data=rss_xml,
        file_name="my_feed.xml",
        mime="application/rss+xml"
    )

# 7. Main Display
if not filtered_entries:
    st.info("No articles found matching that search.")
else:
    for entry in filtered_entries[:30]:
        with st.container():
            # Basic styling since some versions don't support border=True
            st.markdown(f"### [{entry.title}]({entry.link})")
            st.caption(f"Source: {entry.source_name} | Published: {entry.get('published', 'N/A')}")
            
            # Simple Image Logic
            if 'media_content' in entry:
                st.image(entry.media_content[0]['url'], width=300)
            
            st.markdown("---")